"""File containing constants for the project."""

CV_SECTION_HEADERS = ["Education",
                      "Experience",
                      "Technical Projects",
                      "Technical Skills & Languages",
                      "Leadership & Activities",
                      "Work Experience",
                      "Projects",
                      "Skills",
                      "Activities",
                      "Certifications",
                      "Awards",
                      "Publications",
                      "Tech stack",
                      "Interests",
                      "Summary",
                    ]

JOB_DESCRIPTION_SECTION_HEADERS = ["The Job",
                                   "Responsibilities",
                                   "Qualifications",
                                   "Preferred Qualifications",
                                   "About Us",
                                   "Benefits",
                                   "About you",
                                   "Your skills",
                                   ]

REQUIREMENT_KEYWORDS = ["requirement", 
                        "qualification", 
                        "skill", 
                        "responsibility", 
                        "duty", 
                        "must have", 
                        "should have",
                        "experience with",
                        "proficient",
                        "knowledge of",
                        "familiar with",
                        "ability to",
                        "machine learning",
                        "data science",
                        ]

TASKS = ["design",
        "develop",
        "implement",
        "maintain",
        "optimize",
        "build",
        "apply",
        "analyze",
        "crate",
        "deploy",
        "model",
        "deploy",
        "evaluate",
        "conduct",
        "research",
        "collaborate",
        "communicate",
        "lead",
        "manage",
        ]
TECHNICAL_SKILLS = ["python",
                    "java",
                    "c++",
                    "sql",
                    "machine learning",
                    "deep learning",
                    "data analysis",
                    "data visualization",
                    "cloud computing",
                    "aws",
                    "azure",
                    "gcp",
                    "docker",
                    "kubernetes",
                    "git",
                    "linux",]

EXCLUDE = ["equal opportunity",
            "regardless of",
            "disability",
            "benefits",
            "compensation",
            "parental leave",
            "world class",
            "competitive salary",
            "inclusive",
            "diverse",
            "culture",
            "team",
            "collaborate",
            "collaboration",
            "work with",
            "fast-paced",
            "dynamic environment",
            "growth opportunities",
            ]


                